/**
 * 
 */
package AdventOfCode2022;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Stack;

/****************************************************************************
* <b>Title</b>: Day3.java
* <b>Project</b>: lib
* <b>Package</b>: AdventOfCode2022
* <b>Description: </b> FILL IN DESCRIPTION HERE
* 
* @author egeneroli
* @version 1.0
* @since Dec 4, 2022
* @updates:
****************************************************************************/
public class Day7 {
	
	public int calculate2(String input) {
		parseInput(input);
		//System.out.println("root size: " + dirSizeMap.get("/"));
		int remainingSpace = 70000000 - dirSizeMap.get("/");
		//System.out.println("remainingSpace: " + remainingSpace);
		int additionalSpaceNeeded = 30000000 - remainingSpace;
		//System.out.println("additionalSpaceNeeded: " + additionalSpaceNeeded);
		//System.out.println("rootMap: " + rootMap);
		//System.out.println();
		//System.out.println("dirSizeMap: " + dirSizeMap);
		//System.out.println("totalSize: " + totalSize);
		
		return dirSizeMap.values().stream().filter(i -> (i > additionalSpaceNeeded)).mapToInt(i -> i).min().getAsInt();
		
	}
	
	public int calculate(String input) {
		parseInput(input);
		//System.out.println("rootMap: " + rootMap);
		//System.out.println();
		//System.out.println("dirSizeMap: " + dirSizeMap);
		//System.out.println("totalSize: " + totalSize);
		
		return dirSizeMap.values().stream().filter(i -> (i <= 100000)).mapToInt(i -> i).sum();
	}
	
	Map<String, Object> rootMap;
	Map<String, Integer> dirSizeMap;
	long totalSize = 0;
	
	public void parseInput(String input) {
		rootMap = new LinkedHashMap<>();
		rootMap.put("/", new LinkedHashMap<>());
		Map<String, Object> currentMap = (Map) rootMap.get("/");
		
		Stack<String> currentDirPath = new Stack<>();
		for (String line: input.split("\n")) {
			//System.out.println(line);
			String[] lineArray = line.split(" ");
			if (line.startsWith("$ cd")) {
				String cdArg = lineArray[2];
				if (cdArg.equals("/")) {
					currentDirPath = new Stack<>();
					currentDirPath.push("/");
					currentMap = (Map) rootMap.get("/");
				} else if (cdArg.equals("..")) {
					currentDirPath.pop();
					currentMap = getCurrentDirMap(currentDirPath);
				} else {
					currentDirPath.push(cdArg);
					//System.out.println(currentDirPath);
					//System.out.println(currentMap);
					currentMap = (Map) currentMap.get(currentDirPath.peek());
				}
			} else if (line.equals("$ ls")) {
				;
			} else if (line.startsWith("dir")) {
				currentMap.putIfAbsent(lineArray[1], new LinkedHashMap<>());
			} else {
				currentMap.put(lineArray[1], lineArray[0]);
				updateDirSizeMap(currentDirPath, Integer.parseInt(lineArray[0]));
				totalSize += Integer.parseInt(lineArray[0]);
			}
			//System.out.println("currentDirPath: " + currentDirPath);
			//System.out.println("currentMap: " + currentMap);
			//System.out.println("rootMap: " + rootMap);
			//System.out.println();
		}
	}
	
	public void updateDirSizeMap(Stack<String> currentDirPath, int size) {
		
		/*
		Stack<String> currentDirPathTemp = (Stack) currentDirPath.clone();
		for (int i = 0; i < currentDirPathTemp.size(); i++) {
			System.out.println("currentDirPathTemp: " + currentDirPathTemp);
			System.out.println("dirSizeMap: " + dirSizeMap );
			dirSizeMap.putIfAbsent(currentDirPathTemp.peek(), 0);
			dirSizeMap.put(currentDirPathTemp.peek(), dirSizeMap.get(currentDirPathTemp.peek()) + size);
			currentDirPathTemp.pop();
		}
		*/
		
		List<String> currentDirPathList = new ArrayList<>(currentDirPath);
		//System.out.println("currentDirPathList: " + currentDirPathList);
		//incrementIntMapValue(dirSizeMap, "/", size);
		
		for (int i = 1; i <= currentDirPathList.size(); i++) {
			//System.out.println("i: " + i);
			List<String> subList = currentDirPathList.subList(1, i);
			//System.out.println("sublist: " + subList);
			String absPath = "/" + String.join("/", subList);
			//System.out.println("absPath: " + absPath);
			//dirSizeMap.putIfAbsent(absPath, 0);
			//dirSizeMap.put(absPath, dirSizeMap.get(absPath) + size);
			incrementIntMapValue(dirSizeMap, absPath, size);
		}
		//System.out.println();
		//System.out.println();
		//System.out.println("dirSizeMap: " + dirSizeMap);
		
	}
	
	public void incrementIntMapValue(Map<String, Integer> map, String key, int size) {
		map.putIfAbsent(key, 0);
		map.put(key, map.get(key) + size);
	}
	
	public Map<String, Object> getCurrentDirMap(Stack<String> currentDirPath) {
		Map<String, Object> result = rootMap;
		/*
		Stack<String> currentDirPathTemp = (Stack) currentDirPath.clone();
		for (int i = 0; i < currentDirPathTemp.size(); i++) {
			System.out.println("dir: " + currentDirPathTemp.peek());
			System.out.println("result map: " + result);
			System.out.println("map get dir: " + result.get(currentDirPathTemp.peek()));
			result = (Map) result.get(currentDirPathTemp.pop());
		}
		*/
		
		List<String> currentDirPathList = new ArrayList<>(currentDirPath);
		for (String dir: currentDirPathList) {
			//System.out.println("dir: " + dir);
			//System.out.println("result map: " + result);
			//System.out.println("map get dir: " + result.get(dir));
			result = (Map) result.get(dir);
		}

		return result;
	}
		
	public void run() {
		//var result = calculate(inputTest);
		var result = calculate2(inputReal);
		System.out.println("result: " + result);
	}
	
	public static void main(String[] args) {
		Day7 kata = new Day7();
		kata.run();
	}
	
	public Day7() {
		readInput();
		dirSizeMap = new LinkedHashMap<>();
	}
	
	String inputTest;
	String inputReal;
	
	public void readInput() {
		inputTest = 
				  "$ cd /\n"
				+ "$ ls\n"
				+ "dir a\n"
				+ "14848514 b.txt\n"
				+ "8504156 c.dat\n"
				+ "dir d\n"
				+ "$ cd a\n"
				+ "$ ls\n"
				+ "dir e\n"
				+ "29116 f\n"
				+ "2557 g\n"
				+ "62596 h.lst\n"
				+ "$ cd e\n"
				+ "$ ls\n"
				+ "584 i\n"
				+ "$ cd ..\n"
				+ "$ cd ..\n"
				+ "$ cd d\n"
				+ "$ ls\n"
				+ "4060174 j\n"
				+ "8033020 d.log\n"
				+ "5626152 d.ext\n"
				+ "7214296 k"
				;
		
		inputReal = 
				  "$ cd /\n"
				  + "$ ls\n"
				  + "dir cvt\n"
				  + "4967 hcqbmwc.gts\n"
				  + "5512 hsbhwb.clj\n"
				  + "dir hvfvt\n"
				  + "dir phwgv\n"
				  + "277125 pwgswq.fld\n"
				  + "42131 qdzr.btl\n"
				  + "dir svw\n"
				  + "144372 vmbnlzgb.wbd\n"
				  + "dir zft\n"
				  + "$ cd cvt\n"
				  + "$ ls\n"
				  + "dir bbgsthsd\n"
				  + "146042 bcqrmp.czf\n"
				  + "dir chhdjtlw\n"
				  + "dir cpcfcc\n"
				  + "dir dch\n"
				  + "dir djb\n"
				  + "dir djfww\n"
				  + "dir drdf\n"
				  + "dir fgbqtjlj\n"
				  + "dir hjsmmj\n"
				  + "243293 hvfvt.qtb\n"
				  + "245795 lrpb\n"
				  + "dir msptbrl\n"
				  + "181756 qlqqmndd.zcb\n"
				  + "18658 rtfzt.tjp\n"
				  + "dir slpc\n"
				  + "$ cd bbgsthsd\n"
				  + "$ ls\n"
				  + "236957 djfww.fcb\n"
				  + "112286 hcqbmwc.gts\n"
				  + "106102 qggjrzts\n"
				  + "$ cd ..\n"
				  + "$ cd chhdjtlw\n"
				  + "$ ls\n"
				  + "226927 cpcfcc\n"
				  + "309815 djfww\n"
				  + "117933 hcqbmwc.gts\n"
				  + "dir mbdrgfzs\n"
				  + "dir pbmcnpzf\n"
				  + "131558 pwgswq.fld\n"
				  + "298691 qlqqmndd.zcb\n"
				  + "$ cd mbdrgfzs\n"
				  + "$ ls\n"
				  + "164331 hvfvt.dvq\n"
				  + "$ cd ..\n"
				  + "$ cd pbmcnpzf\n"
				  + "$ ls\n"
				  + "102120 bjgg.cqd\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd cpcfcc\n"
				  + "$ ls\n"
				  + "15756 ddc\n"
				  + "dir dqc\n"
				  + "dir glm\n"
				  + "dir jbszm\n"
				  + "200345 pwgswq.fld\n"
				  + "145508 qlqqmndd.zcb\n"
				  + "dir vcptbw\n"
				  + "dir zrtm\n"
				  + "$ cd dqc\n"
				  + "$ ls\n"
				  + "dir cpcfcc\n"
				  + "92063 mzp\n"
				  + "dir qmhnvmh\n"
				  + "dir snqqcjlw\n"
				  + "8423 zdjwr.blc\n"
				  + "$ cd cpcfcc\n"
				  + "$ ls\n"
				  + "dir hvfvt\n"
				  + "$ cd hvfvt\n"
				  + "$ ls\n"
				  + "289372 pwgswq.fld\n"
				  + "307397 qlqqmndd.zcb\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd qmhnvmh\n"
				  + "$ ls\n"
				  + "274778 jczjwdl.smd\n"
				  + "194322 ngrrfm\n"
				  + "$ cd ..\n"
				  + "$ cd snqqcjlw\n"
				  + "$ ls\n"
				  + "182851 nprvrgd.tbb\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd glm\n"
				  + "$ ls\n"
				  + "188702 hpq.hgm\n"
				  + "$ cd ..\n"
				  + "$ cd jbszm\n"
				  + "$ ls\n"
				  + "187645 pwgswq.fld\n"
				  + "$ cd ..\n"
				  + "$ cd vcptbw\n"
				  + "$ ls\n"
				  + "dir mgqd\n"
				  + "$ cd mgqd\n"
				  + "$ ls\n"
				  + "157695 rhldvntj.jzm\n"
				  + "268696 rjnngctw\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd zrtm\n"
				  + "$ ls\n"
				  + "218820 bcqrmp.czf\n"
				  + "172319 czpsl.dnf\n"
				  + "180114 hcqbmwc.gts\n"
				  + "165216 hvfvt.nnw\n"
				  + "dir zft\n"
				  + "$ cd zft\n"
				  + "$ ls\n"
				  + "161245 dtqjg.czv\n"
				  + "249888 hpq.hgm\n"
				  + "192037 zft\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd dch\n"
				  + "$ ls\n"
				  + "dir djfww\n"
				  + "dir fzqgwwnf\n"
				  + "dir hqvmq\n"
				  + "dir mmcrzqc\n"
				  + "42136 qlqqmndd.zcb\n"
				  + "dir vdtlh\n"
				  + "dir wfltm\n"
				  + "271200 zrtm\n"
				  + "$ cd djfww\n"
				  + "$ ls\n"
				  + "37427 dct\n"
				  + "204401 hcqbmwc.gts\n"
				  + "283140 jmq\n"
				  + "dir lbrhbc\n"
				  + "154148 pncb.bmp\n"
				  + "53366 vzt.cnn\n"
				  + "$ cd lbrhbc\n"
				  + "$ ls\n"
				  + "dir djfww\n"
				  + "153648 djfww.pps\n"
				  + "308911 mvtjzp.btg\n"
				  + "219150 ncmc\n"
				  + "253604 wqft.ggb\n"
				  + "293759 zft\n"
				  + "$ cd djfww\n"
				  + "$ ls\n"
				  + "24794 hcqbmwc.gts\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd fzqgwwnf\n"
				  + "$ ls\n"
				  + "233720 scdd.pwr\n"
				  + "$ cd ..\n"
				  + "$ cd hqvmq\n"
				  + "$ ls\n"
				  + "dir cdld\n"
				  + "dir cpcfcc\n"
				  + "dir djfww\n"
				  + "85564 hpq.hgm\n"
				  + "dir qnc\n"
				  + "81509 wtnl.crs\n"
				  + "$ cd cdld\n"
				  + "$ ls\n"
				  + "293421 llpltsgn.tqb\n"
				  + "$ cd ..\n"
				  + "$ cd cpcfcc\n"
				  + "$ ls\n"
				  + "230813 cglljgv\n"
				  + "178203 qlqqmndd.zcb\n"
				  + "186410 zrtm.tbt\n"
				  + "$ cd ..\n"
				  + "$ cd djfww\n"
				  + "$ ls\n"
				  + "201830 zrtm\n"
				  + "$ cd ..\n"
				  + "$ cd qnc\n"
				  + "$ ls\n"
				  + "305356 bdf.jrh\n"
				  + "dir zrtm\n"
				  + "$ cd zrtm\n"
				  + "$ ls\n"
				  + "dir bdhdrr\n"
				  + "$ cd bdhdrr\n"
				  + "$ ls\n"
				  + "dir nffdrnb\n"
				  + "$ cd nffdrnb\n"
				  + "$ ls\n"
				  + "301601 nbrjz\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd mmcrzqc\n"
				  + "$ ls\n"
				  + "dir cpcfcc\n"
				  + "264271 hpq.hgm\n"
				  + "208744 tzsjrf.zdc\n"
				  + "274096 zft\n"
				  + "$ cd cpcfcc\n"
				  + "$ ls\n"
				  + "226054 cpcfcc\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd vdtlh\n"
				  + "$ ls\n"
				  + "84229 bzlg.crn\n"
				  + "58668 cpcfcc.zqw\n"
				  + "141409 hpq.hgm\n"
				  + "dir mdgst\n"
				  + "37090 pstsh.qwv\n"
				  + "40357 qlqqmndd.zcb\n"
				  + "dir smr\n"
				  + "dir sqbgcsgh\n"
				  + "dir trp\n"
				  + "$ cd mdgst\n"
				  + "$ ls\n"
				  + "151033 fsmvbpsl.nqr\n"
				  + "$ cd ..\n"
				  + "$ cd smr\n"
				  + "$ ls\n"
				  + "140764 cpcfcc.dpg\n"
				  + "$ cd ..\n"
				  + "$ cd sqbgcsgh\n"
				  + "$ ls\n"
				  + "dir djfww\n"
				  + "263783 dvm\n"
				  + "105219 hpq.hgm\n"
				  + "29647 hwcgv.gvg\n"
				  + "162537 lwjhgh.wmt\n"
				  + "235511 nlw\n"
				  + "dir zwddrdfz\n"
				  + "$ cd djfww\n"
				  + "$ ls\n"
				  + "260084 vcgpvpd\n"
				  + "$ cd ..\n"
				  + "$ cd zwddrdfz\n"
				  + "$ ls\n"
				  + "225632 bhrzzw\n"
				  + "269756 cqq.vrz\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd trp\n"
				  + "$ ls\n"
				  + "233192 vqwngcs\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd wfltm\n"
				  + "$ ls\n"
				  + "140990 djfww\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd djb\n"
				  + "$ ls\n"
				  + "213191 cjwrs.prd\n"
				  + "dir dhvpqt\n"
				  + "dir gtgftm\n"
				  + "dir hvfvt\n"
				  + "208325 jwhp\n"
				  + "301446 qlqqmndd.zcb\n"
				  + "dir qnlbgvf\n"
				  + "dir tps\n"
				  + "dir zft\n"
				  + "dir zrtm\n"
				  + "dir zwnlm\n"
				  + "$ cd dhvpqt\n"
				  + "$ ls\n"
				  + "dir sbcj\n"
				  + "$ cd sbcj\n"
				  + "$ ls\n"
				  + "20611 ggt\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd gtgftm\n"
				  + "$ ls\n"
				  + "179526 qcqbtmvq\n"
				  + "$ cd ..\n"
				  + "$ cd hvfvt\n"
				  + "$ ls\n"
				  + "dir djstcnrt\n"
				  + "dir hggpvn\n"
				  + "dir hvfvt\n"
				  + "63889 hvfvt.tjm\n"
				  + "265836 qlqqmndd.zcb\n"
				  + "105663 zft\n"
				  + "223582 zft.llg\n"
				  + "26037 zzwwg.lqh\n"
				  + "$ cd djstcnrt\n"
				  + "$ ls\n"
				  + "201498 hcqbmwc.gts\n"
				  + "139156 hpq.hgm\n"
				  + "277342 pshgz.rtp\n"
				  + "dir rjb\n"
				  + "257294 rqrb.lhh\n"
				  + "dir tqnbfnt\n"
				  + "313308 zft.dvc\n"
				  + "$ cd rjb\n"
				  + "$ ls\n"
				  + "268438 hpq.hgm\n"
				  + "dir hvfvt\n"
				  + "dir hvwpb\n"
				  + "161024 mzbcgqc.nvw\n"
				  + "137875 pwgswq.fld\n"
				  + "260008 pzzcww\n"
				  + "283261 wnvlrg.tmn\n"
				  + "$ cd hvfvt\n"
				  + "$ ls\n"
				  + "dir dvwqqt\n"
				  + "163397 hcqbmwc.gts\n"
				  + "265154 pwgswq.fld\n"
				  + "dir trsh\n"
				  + "dir vnf\n"
				  + "$ cd dvwqqt\n"
				  + "$ ls\n"
				  + "315187 hcqbmwc.gts\n"
				  + "$ cd ..\n"
				  + "$ cd trsh\n"
				  + "$ ls\n"
				  + "dir ssrdpg\n"
				  + "$ cd ssrdpg\n"
				  + "$ ls\n"
				  + "dir vjdc\n"
				  + "$ cd vjdc\n"
				  + "$ ls\n"
				  + "dir srvdrhdq\n"
				  + "$ cd srvdrhdq\n"
				  + "$ ls\n"
				  + "74145 djfww\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd vnf\n"
				  + "$ ls\n"
				  + "dir djfww\n"
				  + "$ cd djfww\n"
				  + "$ ls\n"
				  + "184018 pwgswq.fld\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd hvwpb\n"
				  + "$ ls\n"
				  + "dir jwpjrcvs\n"
				  + "$ cd jwpjrcvs\n"
				  + "$ ls\n"
				  + "dir cpcfcc\n"
				  + "$ cd cpcfcc\n"
				  + "$ ls\n"
				  + "52191 sdlv\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd tqnbfnt\n"
				  + "$ ls\n"
				  + "dir djfww\n"
				  + "206341 fmpb.lnp\n"
				  + "dir fpsjg\n"
				  + "4589 hcqbmwc.gts\n"
				  + "dir hvfvt\n"
				  + "8796 hvfvt.hdz\n"
				  + "238364 tgcdpjc.fjm\n"
				  + "dir zrtm\n"
				  + "40577 zrtm.fsr\n"
				  + "$ cd djfww\n"
				  + "$ ls\n"
				  + "217182 djfww.rbf\n"
				  + "$ cd ..\n"
				  + "$ cd fpsjg\n"
				  + "$ ls\n"
				  + "52456 djfww\n"
				  + "$ cd ..\n"
				  + "$ cd hvfvt\n"
				  + "$ ls\n"
				  + "dir rqhzvb\n"
				  + "275026 szwgzm.qjd\n"
				  + "dir zbmtstj\n"
				  + "$ cd rqhzvb\n"
				  + "$ ls\n"
				  + "8395 gcmzsd.jzf\n"
				  + "$ cd ..\n"
				  + "$ cd zbmtstj\n"
				  + "$ ls\n"
				  + "39691 qlqqmndd.zcb\n"
				  + "dir qqcdss\n"
				  + "180676 rwl.zwr\n"
				  + "$ cd qqcdss\n"
				  + "$ ls\n"
				  + "106297 zrtm.nsl\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd zrtm\n"
				  + "$ ls\n"
				  + "153478 ldhvt\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd hggpvn\n"
				  + "$ ls\n"
				  + "19109 cpcfcc.fbh\n"
				  + "249168 fnqjc\n"
				  + "207420 qgzsh.pfs\n"
				  + "135472 qlqqmndd.zcb\n"
				  + "$ cd ..\n"
				  + "$ cd hvfvt\n"
				  + "$ ls\n"
				  + "dir djfww\n"
				  + "213659 hcqbmwc.gts\n"
				  + "dir jzdwq\n"
				  + "204021 nvbgf\n"
				  + "185328 qlqqmndd.zcb\n"
				  + "dir zrtm\n"
				  + "$ cd djfww\n"
				  + "$ ls\n"
				  + "180713 rwmm.gjt\n"
				  + "$ cd ..\n"
				  + "$ cd jzdwq\n"
				  + "$ ls\n"
				  + "57424 djfww.qtm\n"
				  + "104960 slq.bfp\n"
				  + "174906 svc\n"
				  + "$ cd ..\n"
				  + "$ cd zrtm\n"
				  + "$ ls\n"
				  + "dir mrtvhht\n"
				  + "$ cd mrtvhht\n"
				  + "$ ls\n"
				  + "188512 djfww.fvm\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd qnlbgvf\n"
				  + "$ ls\n"
				  + "dir fjrhtssv\n"
				  + "46767 jhbnml.lpq\n"
				  + "$ cd fjrhtssv\n"
				  + "$ ls\n"
				  + "198664 fgcc\n"
				  + "245142 tsc.rsd\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd tps\n"
				  + "$ ls\n"
				  + "dir fmlwghjv\n"
				  + "146731 gwch.ttr\n"
				  + "dir jjzmdd\n"
				  + "dir rtltrng\n"
				  + "191609 wff.mqt\n"
				  + "$ cd fmlwghjv\n"
				  + "$ ls\n"
				  + "189227 zrtm.vgg\n"
				  + "$ cd ..\n"
				  + "$ cd jjzmdd\n"
				  + "$ ls\n"
				  + "dir hvfvt\n"
				  + "178057 mpdfrrm\n"
				  + "49493 pwgswq.fld\n"
				  + "220129 sqgfb.flm\n"
				  + "231012 zrmsnmr\n"
				  + "$ cd hvfvt\n"
				  + "$ ls\n"
				  + "dir lbndbhc\n"
				  + "12602 mnclbss\n"
				  + "746 ppw\n"
				  + "$ cd lbndbhc\n"
				  + "$ ls\n"
				  + "49601 cdqvs.gwc\n"
				  + "158670 wvjpchjg\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd rtltrng\n"
				  + "$ ls\n"
				  + "dir cpgh\n"
				  + "115613 hvfvt\n"
				  + "59441 zfs\n"
				  + "$ cd cpgh\n"
				  + "$ ls\n"
				  + "dir djfww\n"
				  + "$ cd djfww\n"
				  + "$ ls\n"
				  + "dir tgt\n"
				  + "$ cd tgt\n"
				  + "$ ls\n"
				  + "dir vqwvqss\n"
				  + "$ cd vqwvqss\n"
				  + "$ ls\n"
				  + "dir bsdrhz\n"
				  + "$ cd bsdrhz\n"
				  + "$ ls\n"
				  + "dir pld\n"
				  + "$ cd pld\n"
				  + "$ ls\n"
				  + "8543 mfs.gsb\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd zft\n"
				  + "$ ls\n"
				  + "dir fhjgg\n"
				  + "$ cd fhjgg\n"
				  + "$ ls\n"
				  + "114494 pwgswq.fld\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd zrtm\n"
				  + "$ ls\n"
				  + "201142 tlhr.rtd\n"
				  + "298232 wlcztszv\n"
				  + "$ cd ..\n"
				  + "$ cd zwnlm\n"
				  + "$ ls\n"
				  + "240023 hcqbmwc.gts\n"
				  + "159126 hpq.hgm\n"
				  + "22101 hvfvt.bfw\n"
				  + "dir ltzl\n"
				  + "dir mtfr\n"
				  + "dir sbw\n"
				  + "dir sqscdjlj\n"
				  + "dir ssf\n"
				  + "$ cd ltzl\n"
				  + "$ ls\n"
				  + "260692 hpq.hgm\n"
				  + "204540 hvfvt\n"
				  + "$ cd ..\n"
				  + "$ cd mtfr\n"
				  + "$ ls\n"
				  + "15391 pwgswq.fld\n"
				  + "$ cd ..\n"
				  + "$ cd sbw\n"
				  + "$ ls\n"
				  + "293226 hcqbmwc.gts\n"
				  + "267478 htllcq\n"
				  + "176349 nlbhcf.vpn\n"
				  + "286577 zft.gds\n"
				  + "$ cd ..\n"
				  + "$ cd sqscdjlj\n"
				  + "$ ls\n"
				  + "128776 gnh\n"
				  + "dir qbdpvcbt\n"
				  + "284505 qlsn.vdq\n"
				  + "$ cd qbdpvcbt\n"
				  + "$ ls\n"
				  + "280709 crv.hgm\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ssf\n"
				  + "$ ls\n"
				  + "13328 djfww.pjn\n"
				  + "19971 hvfvt\n"
				  + "dir zft\n"
				  + "$ cd zft\n"
				  + "$ ls\n"
				  + "97761 dnmnz\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd djfww\n"
				  + "$ ls\n"
				  + "109590 bwfnnf.wpd\n"
				  + "297297 cmht.ljg\n"
				  + "280726 hvfvt\n"
				  + "$ cd ..\n"
				  + "$ cd drdf\n"
				  + "$ ls\n"
				  + "56764 pwgswq.fld\n"
				  + "300547 wqqm\n"
				  + "210698 zrtm.jvq\n"
				  + "$ cd ..\n"
				  + "$ cd fgbqtjlj\n"
				  + "$ ls\n"
				  + "22217 vrmgsz.ctg\n"
				  + "$ cd ..\n"
				  + "$ cd hjsmmj\n"
				  + "$ ls\n"
				  + "232911 bcqrmp.czf\n"
				  + "164656 hcqbmwc.gts\n"
				  + "dir jql\n"
				  + "dir ntd\n"
				  + "dir prgm\n"
				  + "dir psfvhh\n"
				  + "dir zft\n"
				  + "$ cd jql\n"
				  + "$ ls\n"
				  + "212767 zhnhn.lzm\n"
				  + "dir zrtm\n"
				  + "$ cd zrtm\n"
				  + "$ ls\n"
				  + "35950 bcqrmp.czf\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ntd\n"
				  + "$ ls\n"
				  + "dir vml\n"
				  + "$ cd vml\n"
				  + "$ ls\n"
				  + "60833 bcqrmp.czf\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd prgm\n"
				  + "$ ls\n"
				  + "316166 pwgswq.fld\n"
				  + "$ cd ..\n"
				  + "$ cd psfvhh\n"
				  + "$ ls\n"
				  + "152195 pwgswq.fld\n"
				  + "92448 qlqqmndd.zcb\n"
				  + "$ cd ..\n"
				  + "$ cd zft\n"
				  + "$ ls\n"
				  + "95808 hpq.hgm\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd msptbrl\n"
				  + "$ ls\n"
				  + "256069 hpq.hgm\n"
				  + "$ cd ..\n"
				  + "$ cd slpc\n"
				  + "$ ls\n"
				  + "dir djfww\n"
				  + "285380 djfww.gcm\n"
				  + "169898 hcqbmwc.gts\n"
				  + "40914 mnpnhpz\n"
				  + "188062 pwgswq.fld\n"
				  + "dir zrtm\n"
				  + "$ cd djfww\n"
				  + "$ ls\n"
				  + "94935 pwgswq.fld\n"
				  + "70655 qlqqmndd.zcb\n"
				  + "48528 zft.qvh\n"
				  + "$ cd ..\n"
				  + "$ cd zrtm\n"
				  + "$ ls\n"
				  + "160137 hcqbmwc.gts\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd hvfvt\n"
				  + "$ ls\n"
				  + "dir cslthslv\n"
				  + "129407 prwq\n"
				  + "dir vrzfbtt\n"
				  + "$ cd cslthslv\n"
				  + "$ ls\n"
				  + "dir cpcfcc\n"
				  + "158361 hcqbmwc.gts\n"
				  + "$ cd cpcfcc\n"
				  + "$ ls\n"
				  + "dir zpgnczq\n"
				  + "$ cd zpgnczq\n"
				  + "$ ls\n"
				  + "158414 zft\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd vrzfbtt\n"
				  + "$ ls\n"
				  + "185263 nqvvl\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd phwgv\n"
				  + "$ ls\n"
				  + "253690 bzpcj.fcj\n"
				  + "dir wtbr\n"
				  + "168025 zdsh.tnq\n"
				  + "157840 zsdfqb.zbd\n"
				  + "$ cd wtbr\n"
				  + "$ ls\n"
				  + "dir lvgdb\n"
				  + "$ cd lvgdb\n"
				  + "$ ls\n"
				  + "177751 cpcfcc.dzr\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd svw\n"
				  + "$ ls\n"
				  + "dir cpcfcc\n"
				  + "189430 hpq.hgm\n"
				  + "dir ntzbj\n"
				  + "13384 qlqqmndd.zcb\n"
				  + "10333 wdvqhwgl.trq\n"
				  + "161318 zwzp.jsn\n"
				  + "$ cd cpcfcc\n"
				  + "$ ls\n"
				  + "298999 hcqbmwc.gts\n"
				  + "290883 hpq.hgm\n"
				  + "dir qlnntp\n"
				  + "dir vpshs\n"
				  + "5547 wlrmg.bpc\n"
				  + "dir zft\n"
				  + "$ cd qlnntp\n"
				  + "$ ls\n"
				  + "168562 nqds.tqn\n"
				  + "$ cd ..\n"
				  + "$ cd vpshs\n"
				  + "$ ls\n"
				  + "246400 pwgswq.fld\n"
				  + "$ cd ..\n"
				  + "$ cd zft\n"
				  + "$ ls\n"
				  + "235634 hvfvt.hst\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ntzbj\n"
				  + "$ ls\n"
				  + "98777 qlqqmndd.zcb\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd zft\n"
				  + "$ ls\n"
				  + "dir dhnzm\n"
				  + "299292 hvfvt.pvb\n"
				  + "dir ltfb\n"
				  + "dir mrvsjgsq\n"
				  + "dir ntr\n"
				  + "dir swmvhgd\n"
				  + "dir zrtm\n"
				  + "$ cd dhnzm\n"
				  + "$ ls\n"
				  + "267041 bbsj\n"
				  + "$ cd ..\n"
				  + "$ cd ltfb\n"
				  + "$ ls\n"
				  + "242136 bcqrmp.czf\n"
				  + "314862 dgdz\n"
				  + "203160 hcqbmwc.gts\n"
				  + "80422 hgvz\n"
				  + "dir qftjfqfv\n"
				  + "180815 sstl.wzg\n"
				  + "dir wmhm\n"
				  + "dir zft\n"
				  + "dir zszp\n"
				  + "$ cd qftjfqfv\n"
				  + "$ ls\n"
				  + "dir bmmw\n"
				  + "$ cd bmmw\n"
				  + "$ ls\n"
				  + "dir hvfvt\n"
				  + "318039 hvfvt.whc\n"
				  + "17057 pwgswq.fld\n"
				  + "$ cd hvfvt\n"
				  + "$ ls\n"
				  + "170348 brplf.wgv\n"
				  + "156783 hcqbmwc.gts\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd wmhm\n"
				  + "$ ls\n"
				  + "178474 bcqrmp.czf\n"
				  + "dir cmsgv\n"
				  + "dir dcfvrtj\n"
				  + "225393 htjflrs.tlm\n"
				  + "dir hvfvt\n"
				  + "dir nlrs\n"
				  + "273173 nsmdd.glc\n"
				  + "151259 pwgswq.fld\n"
				  + "dir ztqvwjr\n"
				  + "$ cd cmsgv\n"
				  + "$ ls\n"
				  + "dir flgjbjg\n"
				  + "$ cd flgjbjg\n"
				  + "$ ls\n"
				  + "13971 cpcfcc\n"
				  + "20601 qlqqmndd.zcb\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd dcfvrtj\n"
				  + "$ ls\n"
				  + "141992 djfww.djn\n"
				  + "118149 hpq.hgm\n"
				  + "dir qrmqslq\n"
				  + "$ cd qrmqslq\n"
				  + "$ ls\n"
				  + "105940 zrtm.vql\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd hvfvt\n"
				  + "$ ls\n"
				  + "181962 hpq.hgm\n"
				  + "$ cd ..\n"
				  + "$ cd nlrs\n"
				  + "$ ls\n"
				  + "82705 vnfwjf.hhl\n"
				  + "$ cd ..\n"
				  + "$ cd ztqvwjr\n"
				  + "$ ls\n"
				  + "98257 pwgswq.fld\n"
				  + "83864 scv.pbp\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd zft\n"
				  + "$ ls\n"
				  + "183072 rsbfsl.zsj\n"
				  + "$ cd ..\n"
				  + "$ cd zszp\n"
				  + "$ ls\n"
				  + "dir hvfvt\n"
				  + "$ cd hvfvt\n"
				  + "$ ls\n"
				  + "dir djfww\n"
				  + "dir dqdtgjtg\n"
				  + "dir hvfvt\n"
				  + "$ cd djfww\n"
				  + "$ ls\n"
				  + "117037 rnmbsq.zph\n"
				  + "259243 zrtm.znf\n"
				  + "$ cd ..\n"
				  + "$ cd dqdtgjtg\n"
				  + "$ ls\n"
				  + "dir lrbsvng\n"
				  + "59301 zft\n"
				  + "$ cd lrbsvng\n"
				  + "$ ls\n"
				  + "46301 bcqrmp.czf\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd hvfvt\n"
				  + "$ ls\n"
				  + "223277 qlqqmndd.zcb\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd mrvsjgsq\n"
				  + "$ ls\n"
				  + "160189 cpcfcc\n"
				  + "dir lzqf\n"
				  + "232626 pwgswq.fld\n"
				  + "dir rpmfcg\n"
				  + "$ cd lzqf\n"
				  + "$ ls\n"
				  + "135552 bcqrmp.czf\n"
				  + "48083 qlqqmndd.zcb\n"
				  + "dir rbg\n"
				  + "229086 rdswb.cjz\n"
				  + "204486 spbwfrwf.cmj\n"
				  + "$ cd rbg\n"
				  + "$ ls\n"
				  + "dir sjdwsbqq\n"
				  + "$ cd sjdwsbqq\n"
				  + "$ ls\n"
				  + "270621 rhv.shw\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd rpmfcg\n"
				  + "$ ls\n"
				  + "227216 bld.jtn\n"
				  + "dir zft\n"
				  + "$ cd zft\n"
				  + "$ ls\n"
				  + "43056 vzc\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ntr\n"
				  + "$ ls\n"
				  + "dir cmtnqb\n"
				  + "dir djfww\n"
				  + "195371 wffvmql.lrv\n"
				  + "$ cd cmtnqb\n"
				  + "$ ls\n"
				  + "135380 pbng.vhq\n"
				  + "$ cd ..\n"
				  + "$ cd djfww\n"
				  + "$ ls\n"
				  + "dir fmvrrrq\n"
				  + "dir mbhrbss\n"
				  + "dir zrtm\n"
				  + "$ cd fmvrrrq\n"
				  + "$ ls\n"
				  + "dir cpcfcc\n"
				  + "79110 djfww\n"
				  + "300581 ftcdj.wcc\n"
				  + "$ cd cpcfcc\n"
				  + "$ ls\n"
				  + "234211 zsgsm\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd mbhrbss\n"
				  + "$ ls\n"
				  + "149184 djfww.gwh\n"
				  + "185815 rhgw.rmj\n"
				  + "$ cd ..\n"
				  + "$ cd zrtm\n"
				  + "$ ls\n"
				  + "dir zft\n"
				  + "$ cd zft\n"
				  + "$ ls\n"
				  + "310043 bnwvt.fbg\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd swmvhgd\n"
				  + "$ ls\n"
				  + "77547 djfww.jwr\n"
				  + "318547 drggg\n"
				  + "300962 pwgswq.fld\n"
				  + "$ cd ..\n"
				  + "$ cd zrtm\n"
				  + "$ ls\n"
				  + "229319 bflnffjj\n"
				  + "dir djfww\n"
				  + "142526 hvfvt\n"
				  + "232722 jprrf\n"
				  + "94024 ndmf.hdr\n"
				  + "dir vhdhn\n"
				  + "$ cd djfww\n"
				  + "$ ls\n"
				  + "30770 bcqrmp.czf\n"
				  + "$ cd ..\n"
				  + "$ cd vhdhn\n"
				  + "$ ls\n"
				  + "dir djfww\n"
				  + "48261 djfww.frg\n"
				  + "dir gqc\n"
				  + "316163 qlqqmndd.zcb\n"
				  + "$ cd djfww\n"
				  + "$ ls\n"
				  + "104095 cvjlthn.cfl\n"
				  + "223454 hgqwzh\n"
				  + "24715 pwgswq.fld\n"
				  + "283499 qlqqmndd.zcb\n"
				  + "dir zft\n"
				  + "224574 zlnwn\n"
				  + "$ cd zft\n"
				  + "$ ls\n"
				  + "100941 pwgswq.fld\n"
				  + "$ cd ..\n"
				  + "$ cd ..\n"
				  + "$ cd gqc\n"
				  + "$ ls\n"
				  + "156273 wpgwrdl\n"
				;
	}
}
